title: Datahub
theme: just-the-docs
baseurl: "/dhub/dhub-documentatie"
url: "https://docs.kadaster.nl"

color_scheme: dark

nav_external_links_new_tab: true
enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"